services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-rag}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-rag}
      POSTGRES_DB: ${POSTGRES_DB:-ragdb}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - rag_data:/var/lib/postgresql/data
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge
volumes:
  rag_data:
