"""add_markdown_s3_link_to_document

Revision ID: ef2a4fe0b4b9
Revises: 567d2689c19f 
Create Date: 2025-05-28 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef2a4fe0b4b9'
down_revision: Union[str, None] = '567d2689c19f' # Ensure this points to the previous revision
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('markdown_s3_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'markdown_s3_link')
    # ### end Alembic commands ###
